// v0 example/components/cargo/status-badge.tsx
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { RentalStatus, CarStatus } from "@/lib/types";

interface StatusBadgeProps {
  status: RentalStatus | CarStatus;
  size?: "sm" | "md";
}

const rentalStatusConfig: Record<RentalStatus, { label: string; className: string }> = {
  CREATED: { 
    label: "Created", 
    className: "bg-secondary text-secondary-foreground border-secondary" 
  },
  CONFIRMED: { 
    label: "Confirmed", 
    className: "bg-primary/20 text-primary border-primary/30" 
  },
  ISSUED: { 
    label: "Active", 
    className: "bg-cargo-success/20 text-cargo-success border-cargo-success/30" 
  },
  COMPLETED: { 
    label: "Completed", 
    className: "bg-muted text-muted-foreground border-muted" 
  },
  CANCELLED: { 
    label: "Cancelled", 
    className: "bg-destructive/20 text-destructive border-destructive/30" 
  },
};

const carStatusConfig: Record<CarStatus, { label: string; className: string }> = {
  AVAILABLE: { 
    label: "Available", 
    className: "bg-cargo-success/20 text-cargo-success border-cargo-success/30" 
  },
  RENTED: { 
    label: "Rented", 
    className: "bg-cargo-warning/20 text-cargo-warning border-cargo-warning/30" 
  },
  MAINTENANCE: { 
    label: "Maintenance", 
    className: "bg-muted text-muted-foreground border-muted" 
  },
  RESERVED: { 
    label: "Reserved", 
    className: "bg-primary/20 text-primary border-primary/30" 
  },
};

export function StatusBadge({ status, size = "md" }: StatusBadgeProps) {
  const isRentalStatus = ["CREATED", "CONFIRMED", "ISSUED", "COMPLETED", "CANCELLED"].includes(status);
  const config = isRentalStatus 
    ? rentalStatusConfig[status as RentalStatus] 
    : carStatusConfig[status as CarStatus];

  return (
    <Badge 
      variant="outline" 
      className={cn(
        "font-medium",
        config.className,
        size === "sm" ? "text-xs px-2 py-0.5" : "text-sm px-3 py-1"
      )}
    >
      {config.label}
    </Badge>
  );
}

// frontend/src/shared/ui/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { CarStatus, MaintenanceStatus, RentalStatus } from '@/types/entities'
import { humanizeEnum } from '@/utils/format'

const props = withDefaults(
  defineProps<{
    status: CarStatus | RentalStatus | MaintenanceStatus
    size?: 'sm' | 'md'
  }>(),
  {
    size: 'md',
  },
)

const variantMap: Record<string, string> = {
  AVAILABLE: 'status-badge--success',
  RENTED: 'status-badge--warning',
  MAINTENANCE: 'status-badge--muted',
  INACTIVE: 'status-badge--inactive',
  CREATED: 'status-badge--primary',
  CONFIRMED: 'status-badge--info',
  ISSUED: 'status-badge--success',
  COMPLETED: 'status-badge--neutral',
  CANCELLED: 'status-badge--danger',
  SCHEDULED: 'status-badge--primary',
  IN_PROGRESS: 'status-badge--warning',
}

const badgeClass = computed(() => ['status-badge', variantMap[props.status], `status-badge--${props.size}`])
</script>

<template>
  <span :class="badgeClass">
    {{ humanizeEnum(props.status) }}
  </span>
</template>

<style scoped lang="scss">
.status-badge {
  display: inline-flex;
  align-items: center;
  border-radius: var(--radius-md);
  padding: var(--space-1) var(--space-3);
  font-weight: 600;
  border: 1px solid transparent;

  &--sm {
    font-size: var(--font-size-xs);
  }

  &--md {
    font-size: var(--font-size-sm);
  }

  &--success {
    color: rgb(var(--color-success));
    background: rgb(var(--color-success) / 0.12);
    border-color: rgb(var(--color-success) / 0.24);
  }

  &--warning {
    color: rgb(var(--color-warning));
    background: rgb(var(--color-warning) / 0.12);
    border-color: rgb(var(--color-warning) / 0.24);
  }

  &--danger {
    color: rgb(var(--color-error));
    background: rgb(var(--color-error) / 0.12);
    border-color: rgb(var(--color-error) / 0.24);
  }

  &--primary {
    color: rgb(var(--color-accent));
    background: rgb(var(--color-accent) / 0.12);
    border-color: rgb(var(--color-accent) / 0.24);
  }

  &--info {
    color: rgb(var(--color-info));
    background: rgb(var(--color-info) / 0.12);
    border-color: rgb(var(--color-info) / 0.24);
  }

  &--muted {
    color: var(--text-soft);
    background: var(--surface-glass-strong);
    border-color: var(--border-subtle);
  }

  &--inactive,
  &--neutral {
    color: var(--text-muted);
    background: var(--surface-glass);
    border-color: var(--border-subtle);
  }
}
</style>
