// v0 example/components/cargo/status-badge.tsx
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { RentalStatus, CarStatus } from "@/lib/types";

interface StatusBadgeProps {
  status: RentalStatus | CarStatus;
  size?: "sm" | "md";
}

const rentalStatusConfig: Record<RentalStatus, { label: string; className: string }> = {
  CREATED: { 
    label: "Created", 
    className: "bg-secondary text-secondary-foreground border-secondary" 
  },
  CONFIRMED: { 
    label: "Confirmed", 
    className: "bg-primary/20 text-primary border-primary/30" 
  },
  ISSUED: { 
    label: "Active", 
    className: "bg-cargo-success/20 text-cargo-success border-cargo-success/30" 
  },
  COMPLETED: { 
    label: "Completed", 
    className: "bg-muted text-muted-foreground border-muted" 
  },
  CANCELLED: { 
    label: "Cancelled", 
    className: "bg-destructive/20 text-destructive border-destructive/30" 
  },
};

const carStatusConfig: Record<CarStatus, { label: string; className: string }> = {
  AVAILABLE: { 
    label: "Available", 
    className: "bg-cargo-success/20 text-cargo-success border-cargo-success/30" 
  },
  RENTED: { 
    label: "Rented", 
    className: "bg-cargo-warning/20 text-cargo-warning border-cargo-warning/30" 
  },
  MAINTENANCE: { 
    label: "Maintenance", 
    className: "bg-muted text-muted-foreground border-muted" 
  },
  RESERVED: { 
    label: "Reserved", 
    className: "bg-primary/20 text-primary border-primary/30" 
  },
};

export function StatusBadge({ status, size = "md" }: StatusBadgeProps) {
  const isRentalStatus = ["CREATED", "CONFIRMED", "ISSUED", "COMPLETED", "CANCELLED"].includes(status);
  const config = isRentalStatus 
    ? rentalStatusConfig[status as RentalStatus] 
    : carStatusConfig[status as CarStatus];

  return (
    <Badge 
      variant="outline" 
      className={cn(
        "font-medium",
        config.className,
        size === "sm" ? "text-xs px-2 py-0.5" : "text-sm px-3 py-1"
      )}
    >
      {config.label}
    </Badge>
  );
}

// frontend/src/components/common/StatusBadge.vue
<script setup lang="ts">
import type { CarStatus, MaintenanceStatus, RentalStatus } from '@/types/entities'
import { humanizeEnum } from '@/utils/format'

const props = withDefaults(
  defineProps<{
    status: CarStatus | RentalStatus | MaintenanceStatus
    size?: 'sm' | 'md'
  }>(),
  {
    size: 'md',
  },
)

const variants: Record<string, string> = {
  AVAILABLE: 'bg-success/15 text-success ring-success/25',
  RENTED: 'bg-warning/15 text-warning ring-warning/25',
  MAINTENANCE: 'bg-white/10 text-white/75 ring-white/15',
  INACTIVE: 'bg-white/6 text-white/45 ring-white/10',
  CREATED: 'bg-primary/15 text-primary ring-primary/25',
  CONFIRMED: 'bg-sky-500/15 text-sky-300 ring-sky-500/25',
  ISSUED: 'bg-success/15 text-success ring-success/25',
  COMPLETED: 'bg-white/10 text-white/70 ring-white/15',
  CANCELLED: 'bg-danger/15 text-danger ring-danger/25',
  SCHEDULED: 'bg-primary/15 text-primary ring-primary/25',
  IN_PROGRESS: 'bg-warning/15 text-warning ring-warning/25',
}
</script>

<template>
  <span
    class="inline-flex items-center rounded-full px-3 py-1 font-medium ring-1 ring-inset"
    :class="[variants[props.status], props.size === 'sm' ? 'text-xs' : 'text-sm']"
  >
    {{ humanizeEnum(props.status) }}
  </span>
</template>
